GET http://localhost:3000/places?text=av padre lourenço da costa, 3415, Itajubá, MG

###
GET http://localhost:3000/places?text=av doutor luiz renno, 61, Itajubá, MG

### 
@originId=ElpBdi4gUGFkcmUgTG91cmVuw6dvIGRhIENvc3RhLVJvZG92aWEgQnItNDU5LCAzNDE1IC0gVmFyZ2luaGEsIEl0YWp1YsOhIC0gTUcsIDM3NTAxLCBCcmFzaWwiMRIvChQKEglLk_GpH2PLlBEGLEsjWE_cGhDXGioUChIJWfwY-CBjy5QRjuZnlYWKvKI
@destinationId=ChIJWwAH-a98y5QR1Ft6JaVSJ_E

###
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}

###
POST http://localhost:3000/routes
Content-Type: application/json

{ 
  "name": "rota 1",
  "source_id": "{{ originId }}",
  "destination_id": "{{ destinationId }}"
}

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/67638a8be73069e6c342453b